# Generated by Django 4.2.7 on 2023-11-17 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institute",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="institute"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="specialization"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            managers=[
                ("teachers", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="Student",
            name="prefer_teacher",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.teacher",
            ),
        ),
    ]
