# Generated by Django 4.2.7 on 2023-11-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_delete_teacher_teacher_alter_student_prefer_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="role",
            field=models.CharField(
                default="TEACHER", max_length=50, verbose_name="role"
            ),
        ),
    ]
