# Generated by Django 4.2.7 on 2023-11-17 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_teacher_managers"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institute",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="institute"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="specialization"
                    ),
                ),
                (
                    "graduate_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        validators=[users.utils.year_validation],
                        verbose_name="graduate year",
                    ),
                ),
                (
                    "theme",
                    models.CharField(blank=True, max_length=150, verbose_name="theme"),
                ),
                (
                    "prefer_teacher",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.teacher",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
