# Generated by Django 4.2.7 on 2023-11-17 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_delete_student_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="role",
        ),
    ]
