# Generated by Django 4.2.7 on 2023-11-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_student_prefer_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("TEACHER", "Teacher"),
                    ("STUDENT", "Student"),
                ],
                default="ADMIN",
                max_length=50,
                verbose_name="role",
            ),
        ),
    ]
