# Generated by Django 4.2.7 on 2023-11-17 09:00

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="graduate_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[users.utils.year_validation],
                verbose_name="graduate year",
            ),
        ),
    ]
