version: '3.8'

services:
  back:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/config
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env

#  front:
#    image: nginx
#    container_name: frontend

volumes:
  postgres_data: