# Generated by Django 4.2.7 on 2023-12-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("directions", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="direction",
            field=models.ForeignKey(
                blank=True,
                max_length=150,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="directions.direction",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="institute",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="directions.institute",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="prefer_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="users.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="direction",
            field=models.ForeignKey(
                blank=True,
                max_length=150,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="directions.direction",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="institute",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="directions.institute",
            ),
        ),
    ]
