# Generated by Django 4.2.7 on 2023-12-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("topic_choice", "Выбор темы"),
                    ("theoretical_aspects", "Изучение теоретических аспектов темы"),
                    ("data_collection_and_analysis", "Сбор и анализ данных"),
                    ("main_wokr", "Написание основной части / Разработка"),
                    ("decorator_fqw", "Оформление ВКР"),
                    ("finished", "Завершено"),
                ],
                default="topic_choice",
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
