# Generated by Django 4.2.7 on 2023-12-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_student_direction_alter_student_institute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("topic_choice", "Выбор темы"),
                    (
                        "theoretical_aspects",
                        "Изучение теоретических аспектов темы работы",
                    ),
                    ("data_collection_and_analysis", "Сбор и анализ данных"),
                    ("main_wokr", "Написание основной части / Разработка"),
                    ("decorator_fqw", "Оформление ВКР"),
                    ("finished", "Завершено"),
                ],
                default="topic_choice",
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
