# Generated by Django 4.2.7 on 2023-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_student_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.CharField(blank=True, max_length=10, verbose_name="group"),
        ),
    ]
